<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CowColonySim.Sim</RootNamespace>
    <AssemblyName>CowColonySim.Sim</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Friflo.Engine.ECS" Version="3.4.0" />
  </ItemGroup>
</Project>
